eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
      metadata-map:
        cluster: HELLO
server:
  port: 8082